drchubo_fullbody_interface:

  drchubo_fullbody_feedback_node:
    joints:
      - TSY
      - NKY
      - NK1
      - NK2
      - LSP
      - LSR
      - LSY
      - LEP
      - LWY
      - LWP
      - LWR
      - RSP
      - RSR
      - RSY
      - REP
      - RWY
      - RWP
      - RWR
      - LHY
      - LHR
      - LHP
      - LKP
      - LAP
      - LAR
      - RHY
      - RHR
      - RHP
      - RKP
      - RAP
      - RAR
    mapping:
      TSY:
        huboachid: 0
      NKY:
        huboachid: 1
      NK1:
        huboachid: 2
      NK2:
        huboachid: 3
      LSP:
        huboachid: 4
      LSR:
        huboachid: 5
      LSY:
        huboachid: 6
      LEP:
        huboachid: 7
      LWY:
        huboachid: 8
      LWP:
        huboachid: 10
      LWR:
        huboachid: 9
      RSP:
        huboachid: 11
      RSR:
        huboachid: 12
      RSY:
        huboachid: 13
      REP:
        huboachid: 14
      RWY:
        huboachid: 15
      RWP:
        huboachid: 17
      RWR:
        huboachid: 16
      LHY:
        huboachid: 19
      LHR:
        huboachid: 20
      LHP:
        huboachid: 21
      LKP:
        huboachid: 22
      LAP:
        huboachid: 23
      LAR:
        huboachid: 24
      RHY:
        huboachid: 26
      RHR:
        huboachid: 27
      RHP:
        huboachid: 28
      RKP:
        huboachid: 29
      RAP:
        huboachid: 30
      RAR:
        huboachid: 31

  drchubo_fullbody_feedforward_node:
    joints:
      - TSY
      - NKY
      - NK1
      - NK2
      - LSP
      - LSR
      - LSY
      - LEP
      - LWY
      - LWP
      - LWR
      - RSP
      - RSR
      - RSY
      - REP
      - RWY
      - RWP
      - RWR
      - LHY
      - LHR
      - LHP
      - LKP
      - LAP
      - LAR
      - RHY
      - RHR
      - RHP
      - RKP
      - RAP
      - RAR
    mapping:
      TSY:
        huboachid: 0
      NKY:
        huboachid: 1
      NK1:
        huboachid: 2
      NK2:
        huboachid: 3
      LSP:
        huboachid: 4
      LSR:
        huboachid: 5
      LSY:
        huboachid: 6
      LEP:
        huboachid: 7
      LWY:
        huboachid: 8
      LWP:
        huboachid: 10
      LWR:
        huboachid: 9
      RSP:
        huboachid: 11
      RSR:
        huboachid: 12
      RSY:
        huboachid: 13
      REP:
        huboachid: 14
      RWY:
        huboachid: 15
      RWP:
        huboachid: 17
      RWR:
        huboachid: 16
      LHY:
        huboachid: 19
      LHR:
        huboachid: 20
      LHP:
        huboachid: 21
      LKP:
        huboachid: 22
      LAP:
        huboachid: 23
      LAR:
        huboachid: 24
      RHY:
        huboachid: 26
      RHR:
        huboachid: 27
      RHP:
        huboachid: 28
      RKP:
        huboachid: 29
      RAP:
        huboachid: 30
      RAR:
        huboachid: 31
