huboplus_fullbody_interface:

  huboplus_fullbody_feedback_node:
    joints:
      - HPY
      - HNR
      - HNP
      - LSP
      - LSR
      - LSY
      - LEP
      - LWY
      - LWP
      - LWR
      - RSP
      - RSR
      - RSY
      - REP
      - RWY
      - RWP
      - RWR
      - LHY
      - LHR
      - LHP
      - LKP
      - LAP
      - LAR
      - RHY
      - RHR
      - RHP
      - RKP
      - RAP
      - RAR
    mapping:
      HPY:
        huboachid: 0
      HNR:
        huboachid: 2
      HNP:
        huboachid: 3
      LSP:
        huboachid: 4
      LSR:
        huboachid: 5
      LSY:
        huboachid: 6
      LEP:
        huboachid: 7
      LWY:
        huboachid: 8
      LWP:
        huboachid: 10
      RSP:
        huboachid: 11
      RSR:
        huboachid: 12
      RSY:
        huboachid: 13
      REP:
        huboachid: 14
      RWY:
        huboachid: 15
      RWP:
        huboachid: 17
      LHY:
        huboachid: 19
      LHR:
        huboachid: 20
      LHP:
        huboachid: 21
      LKP:
        huboachid: 22
      LAP:
        huboachid: 23
      LAR:
        huboachid: 24
      RHY:
        huboachid: 26
      RHR:
        huboachid: 27
      RHP:
        huboachid: 28
      RKP:
        huboachid: 29
      RAP:
        huboachid: 30
      RAR:
        huboachid: 31
      RF1:
        huboachid: 32
      RF2:
        huboachid: 33
      RF3:
        huboachid: 34
      RF4:
        huboachid: 35
      RF5:
        huboachid: 36
      LF1:
        huboachid: 37
      LF2:
        huboachid: 38
      LF3:
        huboachid: 39
      LF4:
        huboachid: 40
      LF5:
        huboachid: 41

  huboplus_fullbody_feedforward_node:
    joints:
      - HPY
      - HNR
      - HNP
      - LSP
      - LSR
      - LSY
      - LEP
      - LWY
      - LWP
      - LWR
      - RSP
      - RSR
      - RSY
      - REP
      - RWY
      - RWP
      - RWR
      - LHY
      - LHR
      - LHP
      - LKP
      - LAP
      - LAR
      - RHY
      - RHR
      - RHP
      - RKP
      - RAP
      - RAR
    mapping:
      HPY:
        huboachid: 0
      HNR:
        huboachid: 2
      HNP:
        huboachid: 3
      LSP:
        huboachid: 4
      LSR:
        huboachid: 5
      LSY:
        huboachid: 6
      LEP:
        huboachid: 7
      LWY:
        huboachid: 8
      LWP:
        huboachid: 10
      RSP:
        huboachid: 11
      RSR:
        huboachid: 12
      RSY:
        huboachid: 13
      REP:
        huboachid: 14
      RWY:
        huboachid: 15
      RWP:
        huboachid: 17
      LHY:
        huboachid: 19
      LHR:
        huboachid: 20
      LHP:
        huboachid: 21
      LKP:
        huboachid: 22
      LAP:
        huboachid: 23
      LAR:
        huboachid: 24
      RHY:
        huboachid: 26
      RHR:
        huboachid: 27
      RHP:
        huboachid: 28
      RKP:
        huboachid: 29
      RAP:
        huboachid: 30
      RAR:
        huboachid: 31
      RF1:
        huboachid: 32
      RF2:
        huboachid: 33
      RF3:
        huboachid: 34
      RF4:
        huboachid: 35
      RF5:
        huboachid: 36
      LF1:
        huboachid: 37
      LF2:
        huboachid: 38
      LF3:
        huboachid: 39
      LF4:
        huboachid: 40
      LF5:
        huboachid: 41
