hubo_fullbody_controller:

  hubo_fullbody_action_node:
    joints:
      - HPY
      - HNR
      - HNP
      - LSP
      - LSR
      - LSY
      - LEP
      - LWY
      - LWP
      - RSP
      - RSR
      - RSY
      - REP
      - RWY
      - RWP
      - LHY
      - LHR
      - LHP
      - LKP
      - LAP
      - LAR
      - RHY
      - RHR
      - RHP
      - RKP
      - RAP
      - RAR
    constraints:
      goal_time: 0.6
      HPY:
        goal: 0.50
      HNR:
        goal: 0.02
      HNP:
        goal: 0.02
      LSP:
        goal: 0.02
      LSR:
        goal: 0.02
      LSY:
        goal: 0.02
      LEP:
        goal: 0.02
      LWY:
        goal: 0.02
      LWP:
        goal: 0.02
      RSP:
        goal: 0.02
      RSR:
        goal: 0.02
      RSY:
        goal: 0.02
      REP:
        goal: 0.02
      RWY:
        goal: 0.02
      RWP:
        goal: 0.02
      LHY:
        goal: 0.02
      LHR:
        goal: 0.02
      LHP:
        goal: 0.02
      LKP:
        goal: 0.02
      LAP:
        goal: 0.02
      LAR:
        goal: 0.02
      RHY:
        goal: 0.02
      RHR:
        goal: 0.02
      RHP:
        goal: 0.02
      RKP:
        goal: 0.02
      RAP:
        goal: 0.02
      RAR:
        goal: 0.02

  hubo_fullbody_controller_node:
    joints:
      - HPY
      - HNR
      - HNP
      - LSP
      - LSR
      - LSY
      - LEP
      - LWY
      - LWP
      - RSP
      - RSR
      - RSY
      - REP
      - RWY
      - RWP
      - LHY
      - LHR
      - LHP
      - LKP
      - LAP
      - LAR
      - RHY
      - RHR
      - RHP
      - RKP
      - RAP
      - RAR
    mapping:
      HPY:
        huboachid: 0
      HNR:
        huboachid: 2
      HNP:
        huboachid: 3
      LSP:
        huboachid: 4
      LSR:
        huboachid: 5
      LSY:
        huboachid: 6
      LEP:
        huboachid: 7
      LWY:
        huboachid: 8
      LWP:
        huboachid: 10
      RSP:
        huboachid: 11
      RSR:
        huboachid: 12
      RSY:
        huboachid: 13
      REP:
        huboachid: 14
      RWY:
        huboachid: 15
      RWP:
        huboachid: 17
      LHY:
        huboachid: 18
      LHR:
        huboachid: 19
      LHP:
        huboachid: 20
      LKP:
        huboachid: 21
      LAP:
        huboachid: 22
      LAR:
        huboachid: 23
      RHY:
        huboachid: 24
      RHR:
        huboachid: 25
      RHP:
        huboachid: 26
      RKP:
        huboachid: 27
      RAP:
        huboachid: 28
      RAR:
        huboachid: 29
