float64 FingerPosition
float64 FingerEffort
float64 TriggerPosition
float64 TriggerEffort
---
float64 FingerPosition
float64 FingerEffort
float64 TriggerPosition
float64 TriggerEffort
---
float64 FingerPosition
float64 FingerEffort
float64 TriggerPosition
float64 TriggerEffort
